# Resource: https://geshan.com.np/blog/2022/01/redis-docker/

services:
  web-app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8080:80"
    depends_on:
      - database
      - cache

  database:
    image: docker.io/library/mariadb:latest
    container_name: dev-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: __test__1234
      MARIADB_DATABASE: shopfront_db
      MARIADB_USER: shopfront
      MARIADB_PASSWORD: __test__1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql:Z

  cache:
    image: docker.io/library/redis:latest
    container_name: dev-redis
    restart: always
    environment:
      REDIS_DB: 0
      REDIS_HOST: shopfront_cache
      REDIS_USER: shopfront
      REDIS_PASSWORD: __test__1234
      REDIS_PORT: 6379
    command: ["redis-server", "--user", "default", "off", "--user", "${REDIS_USER}", "on", ">${REDIS_PASSWORD}", "~*", "+@all"]
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  mariadb-data:
    driver: local 
  cache:
    driver: local
