 ssl:
   cert: ./ssl/cert.pem
   key: ./ssl/key.pem
   conf: []
 listeners:
   - address: 0.0.0.0
     port: 8080
     https: false
   - address: 0.0.0.0
     port: 4443
     https: true
     cert: ''
     key: ''
     use_old_tls: false
     ssl_conf: []
 db_clients:
   - name: default
     rdbms: mysql
     host: 127.0.0.1
     port: 3306
     dbname: shopfront_db
     user: 'shopfront'
     passwd: '__test__1234'
     is_fast: true
     number_of_connections: 1
     timeout: -1
# redis_clients:
#     # name: Name of the client,'default' by default
#   - name: default
#     # host: Server IP, 127.0.0.1 by default
#     host: 127.0.0.1
#     # port: Server port, 6379 by default
#     port: 6379
#     # username: '' by default which means 'default' in redis ACL
#     username: ''
#     # passwd: '' by default
#     passwd: ''
#     # db index: 0 by default
#     db: 0
#     # is_fast: false by default, if it is true, the client is faster but user can't call
#     # any synchronous interface of it.
#     is_fast: false
#     # number_of_connections: 1 by default, if the 'is_fast' is true, the number is the number of  
#     # connections per IO thread, otherwise it is the total number of all connections.  
#     number_of_connections: 1
#     # timeout: -1.0 by default, in seconds, the timeout for executing a command.
#     # zero or negative value means no timeout.
#     timeout: -1
 app: 
  # 1 for testing, 0 for production
  number_of_threads: 1
  enable_session: false
  session_timeout: 0
  session_same_site: 'Null'
  session_cookie_key: 'JSESSIONID'
  session_max_age: -1
  document_root: ./public_html
  home_page: index.html
  use_implicit_page: true
  implicit_page: index.html
  upload_path: uploads
  file_types:
    - gif
    - png
    - jpg
    - js
    - css
    - html
    - ico
    - swf
    - xap
    - apk
    - cur
    - xml
  mime: {}
  locations:
    - uri_prefix: '' # /.well-known/acme-challenge/
      default_content_type: text/plain
      alias: ''
      is_case_sensitive: false
      allow_all: true
      is_recursive: true
      filters: []
  max_connections: 100000
  max_connections_per_ip: 0
  load_dynamic_views: false
  dynamic_views_path:
    - ./views
  dynamic_views_output_path: ''
  json_parser_stack_limit: 1000
  enable_unicode_escaping_in_json: true
  float_precision_in_json:
    precision: 0
    precision_type: significant
  log:
    use_spdlog: false
    logfile_base_name: ''
    log_size_limit: 100000000
    max_files: 0
    log_level: DEBUG
    display_local_time: false
  run_as_daemon: false
  handle_sig_term: true
  relaunch_on_error: false
  use_sendfile: true
  use_gzip: true
  use_brotli: false
  static_files_cache_time: 5
  idle_connection_timeout: 60
  server_header_field: ''
  enable_server_header: true
  enable_date_header: true
  keepalive_requests: 0
  pipelining_requests: 0
  gzip_static: true
  br_static: true
  client_max_body_size: 1M
  client_max_memory_body_size: 64K
  client_max_websocket_message_size: 128K
  reuse_port: false
  enabled_compressed_request: false
  enable_request_stream: false
 plugins:
  - name: drogon::plugin::PromExporter
    dependencies: []
    config:
      path: /metrics
  - name: drogon::plugin::AccessLogger
    dependencies: []
    config:
      use_spdlog: false
      log_path: ''
      log_format: ''
      log_file: access.log
      log_size_limit: 0
      use_local_time: true
      log_index: 0
 custom_config: {}
