/**
 *
 *  Products.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Products.h"
#include "Shops.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::shopfront_db;

const std::string Products::Cols::_productId = "productId";
const std::string Products::Cols::_productName = "productName";
const std::string Products::Cols::_productPrice = "productPrice";
const std::string Products::Cols::_shopId = "shopId";
const std::string Products::primaryKeyName = "productId";
const bool Products::hasPrimaryKey = true;
const std::string Products::tableName = "products";

const std::vector<typename Products::MetaData> Products::metaData_={
{"productId","int32_t","int(11)",4,1,1,1},
{"productName","std::string","varchar(255)",255,0,0,0},
{"productPrice","std::string","decimal(6,2)",0,0,0,0},
{"shopId","int32_t","int(11)",4,0,0,0}
};
const std::string &Products::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Products::Products(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["productId"].isNull())
        {
            productid_=std::make_shared<int32_t>(r["productId"].as<int32_t>());
        }
        if(!r["productName"].isNull())
        {
            productname_=std::make_shared<std::string>(r["productName"].as<std::string>());
        }
        if(!r["productPrice"].isNull())
        {
            productprice_=std::make_shared<std::string>(r["productPrice"].as<std::string>());
        }
        if(!r["shopId"].isNull())
        {
            shopid_=std::make_shared<int32_t>(r["shopId"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            productid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            productname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            productprice_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            shopid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Products::Products(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            productid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            productname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            productprice_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

Products::Products(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("productId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["productId"].isNull())
        {
            productid_=std::make_shared<int32_t>((int32_t)pJson["productId"].asInt64());
        }
    }
    if(pJson.isMember("productName"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["productName"].isNull())
        {
            productname_=std::make_shared<std::string>(pJson["productName"].asString());
        }
    }
    if(pJson.isMember("productPrice"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["productPrice"].isNull())
        {
            productprice_=std::make_shared<std::string>(pJson["productPrice"].asString());
        }
    }
    if(pJson.isMember("shopId"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["shopId"].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson["shopId"].asInt64());
        }
    }
}

void Products::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            productid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            productname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            productprice_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

void Products::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("productId"))
    {
        if(!pJson["productId"].isNull())
        {
            productid_=std::make_shared<int32_t>((int32_t)pJson["productId"].asInt64());
        }
    }
    if(pJson.isMember("productName"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["productName"].isNull())
        {
            productname_=std::make_shared<std::string>(pJson["productName"].asString());
        }
    }
    if(pJson.isMember("productPrice"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["productPrice"].isNull())
        {
            productprice_=std::make_shared<std::string>(pJson["productPrice"].asString());
        }
    }
    if(pJson.isMember("shopId"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["shopId"].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson["shopId"].asInt64());
        }
    }
}

const int32_t &Products::getValueOfProductid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(productid_)
        return *productid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Products::getProductid() const noexcept
{
    return productid_;
}
void Products::setProductid(const int32_t &pProductid) noexcept
{
    productid_ = std::make_shared<int32_t>(pProductid);
    dirtyFlag_[0] = true;
}
const typename Products::PrimaryKeyType & Products::getPrimaryKey() const
{
    assert(productid_);
    return *productid_;
}

const std::string &Products::getValueOfProductname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(productname_)
        return *productname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Products::getProductname() const noexcept
{
    return productname_;
}
void Products::setProductname(const std::string &pProductname) noexcept
{
    productname_ = std::make_shared<std::string>(pProductname);
    dirtyFlag_[1] = true;
}
void Products::setProductname(std::string &&pProductname) noexcept
{
    productname_ = std::make_shared<std::string>(std::move(pProductname));
    dirtyFlag_[1] = true;
}
void Products::setProductnameToNull() noexcept
{
    productname_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Products::getValueOfProductprice() const noexcept
{
    static const std::string defaultValue = std::string();
    if(productprice_)
        return *productprice_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Products::getProductprice() const noexcept
{
    return productprice_;
}
void Products::setProductprice(const std::string &pProductprice) noexcept
{
    productprice_ = std::make_shared<std::string>(pProductprice);
    dirtyFlag_[2] = true;
}
void Products::setProductprice(std::string &&pProductprice) noexcept
{
    productprice_ = std::make_shared<std::string>(std::move(pProductprice));
    dirtyFlag_[2] = true;
}
void Products::setProductpriceToNull() noexcept
{
    productprice_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &Products::getValueOfShopid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(shopid_)
        return *shopid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Products::getShopid() const noexcept
{
    return shopid_;
}
void Products::setShopid(const int32_t &pShopid) noexcept
{
    shopid_ = std::make_shared<int32_t>(pShopid);
    dirtyFlag_[3] = true;
}
void Products::setShopidToNull() noexcept
{
    shopid_.reset();
    dirtyFlag_[3] = true;
}

void Products::updateId(const uint64_t id)
{
    productid_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Products::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "productName",
        "productPrice",
        "shopId"
    };
    return inCols;
}

void Products::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProductname())
        {
            binder << getValueOfProductname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProductprice())
        {
            binder << getValueOfProductprice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getShopid())
        {
            binder << getValueOfShopid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Products::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Products::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProductname())
        {
            binder << getValueOfProductname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProductprice())
        {
            binder << getValueOfProductprice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getShopid())
        {
            binder << getValueOfShopid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Products::toJson() const
{
    Json::Value ret;
    if(getProductid())
    {
        ret["productId"]=getValueOfProductid();
    }
    else
    {
        ret["productId"]=Json::Value();
    }
    if(getProductname())
    {
        ret["productName"]=getValueOfProductname();
    }
    else
    {
        ret["productName"]=Json::Value();
    }
    if(getProductprice())
    {
        ret["productPrice"]=getValueOfProductprice();
    }
    else
    {
        ret["productPrice"]=Json::Value();
    }
    if(getShopid())
    {
        ret["shopId"]=getValueOfShopid();
    }
    else
    {
        ret["shopId"]=Json::Value();
    }
    return ret;
}

std::string Products::toString() const
{
    return toJson().toStyledString();
}

Json::Value Products::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getProductid())
            {
                ret[pMasqueradingVector[0]]=getValueOfProductid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProductname())
            {
                ret[pMasqueradingVector[1]]=getValueOfProductname();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getProductprice())
            {
                ret[pMasqueradingVector[2]]=getValueOfProductprice();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getShopid())
            {
                ret[pMasqueradingVector[3]]=getValueOfShopid();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getProductid())
    {
        ret["productId"]=getValueOfProductid();
    }
    else
    {
        ret["productId"]=Json::Value();
    }
    if(getProductname())
    {
        ret["productName"]=getValueOfProductname();
    }
    else
    {
        ret["productName"]=Json::Value();
    }
    if(getProductprice())
    {
        ret["productPrice"]=getValueOfProductprice();
    }
    else
    {
        ret["productPrice"]=Json::Value();
    }
    if(getShopid())
    {
        ret["shopId"]=getValueOfShopid();
    }
    else
    {
        ret["shopId"]=Json::Value();
    }
    return ret;
}

bool Products::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("productId"))
    {
        if(!validJsonOfField(0, "productId", pJson["productId"], err, true))
            return false;
    }
    if(pJson.isMember("productName"))
    {
        if(!validJsonOfField(1, "productName", pJson["productName"], err, true))
            return false;
    }
    if(pJson.isMember("productPrice"))
    {
        if(!validJsonOfField(2, "productPrice", pJson["productPrice"], err, true))
            return false;
    }
    if(pJson.isMember("shopId"))
    {
        if(!validJsonOfField(3, "shopId", pJson["shopId"], err, true))
            return false;
    }
    return true;
}
bool Products::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Products::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("productId"))
    {
        if(!validJsonOfField(0, "productId", pJson["productId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("productName"))
    {
        if(!validJsonOfField(1, "productName", pJson["productName"], err, false))
            return false;
    }
    if(pJson.isMember("productPrice"))
    {
        if(!validJsonOfField(2, "productPrice", pJson["productPrice"], err, false))
            return false;
    }
    if(pJson.isMember("shopId"))
    {
        if(!validJsonOfField(3, "shopId", pJson["shopId"], err, false))
            return false;
    }
    return true;
}
bool Products::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Products::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Shops Products::getShops(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from shops where shopId = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *shopid_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Shops(r[0]);
}

void Products::getShops(const DbClientPtr &clientPtr,
                        const std::function<void(Shops)> &rcb,
                        const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from shops where shopId = ?";
    *clientPtr << sql
               << *shopid_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Shops(r[0]));
                    }
               }
               >> ecb;
}
