/**
 *
 *  Products.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace shopfront_db
{
class Shops;

class Products
{
  public:
    struct Cols
    {
        static const std::string _productId;
        static const std::string _productName;
        static const std::string _productPrice;
        static const std::string _shopId;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Products(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Products(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Products(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Products() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column productId  */
    ///Get the value of the column productId, returns the default value if the column is null
    const int32_t &getValueOfProductid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getProductid() const noexcept;
    ///Set the value of the column productId
    void setProductid(const int32_t &pProductid) noexcept;

    /**  For column productName  */
    ///Get the value of the column productName, returns the default value if the column is null
    const std::string &getValueOfProductname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProductname() const noexcept;
    ///Set the value of the column productName
    void setProductname(const std::string &pProductname) noexcept;
    void setProductname(std::string &&pProductname) noexcept;
    void setProductnameToNull() noexcept;

    /**  For column productPrice  */
    ///Get the value of the column productPrice, returns the default value if the column is null
    const std::string &getValueOfProductprice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProductprice() const noexcept;
    ///Set the value of the column productPrice
    void setProductprice(const std::string &pProductprice) noexcept;
    void setProductprice(std::string &&pProductprice) noexcept;
    void setProductpriceToNull() noexcept;

    /**  For column shopId  */
    ///Get the value of the column shopId, returns the default value if the column is null
    const int32_t &getValueOfShopid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getShopid() const noexcept;
    ///Set the value of the column shopId
    void setShopid(const int32_t &pShopid) noexcept;
    void setShopidToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 4;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Shops getShops(const drogon::orm::DbClientPtr &clientPtr) const;
    void getShops(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(Shops)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Products>;
    friend drogon::orm::BaseBuilder<Products, true, true>;
    friend drogon::orm::BaseBuilder<Products, true, false>;
    friend drogon::orm::BaseBuilder<Products, false, true>;
    friend drogon::orm::BaseBuilder<Products, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Products>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> productid_;
    std::shared_ptr<std::string> productname_;
    std::shared_ptr<std::string> productprice_;
    std::shared_ptr<int32_t> shopid_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[4]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where productId = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where productId = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "productId,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "productName,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "productPrice,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "shopId,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace shopfront_db
} // namespace drogon_model
