/**
 *
 *  Shops.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Shops.h"
#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::shopfront_db;

const std::string Shops::Cols::_shopId = "shopId";
const std::string Shops::Cols::_shopName = "shopName";
const std::string Shops::Cols::_ownerId = "ownerId";
const std::string Shops::primaryKeyName = "shopId";
const bool Shops::hasPrimaryKey = true;
const std::string Shops::tableName = "shops";

const std::vector<typename Shops::MetaData> Shops::metaData_={
{"shopId","int32_t","int(11)",4,1,1,1},
{"shopName","std::string","varchar(255)",255,0,0,0},
{"ownerId","int32_t","int(11)",4,0,0,0}
};
const std::string &Shops::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Shops::Shops(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["shopId"].isNull())
        {
            shopid_=std::make_shared<int32_t>(r["shopId"].as<int32_t>());
        }
        if(!r["shopName"].isNull())
        {
            shopname_=std::make_shared<std::string>(r["shopName"].as<std::string>());
        }
        if(!r["ownerId"].isNull())
        {
            ownerid_=std::make_shared<int32_t>(r["ownerId"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            shopid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            shopname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            ownerid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Shops::Shops(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            shopname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            ownerid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

Shops::Shops(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("shopId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["shopId"].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson["shopId"].asInt64());
        }
    }
    if(pJson.isMember("shopName"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["shopName"].isNull())
        {
            shopname_=std::make_shared<std::string>(pJson["shopName"].asString());
        }
    }
    if(pJson.isMember("ownerId"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["ownerId"].isNull())
        {
            ownerid_=std::make_shared<int32_t>((int32_t)pJson["ownerId"].asInt64());
        }
    }
}

void Shops::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            shopname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            ownerid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void Shops::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("shopId"))
    {
        if(!pJson["shopId"].isNull())
        {
            shopid_=std::make_shared<int32_t>((int32_t)pJson["shopId"].asInt64());
        }
    }
    if(pJson.isMember("shopName"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["shopName"].isNull())
        {
            shopname_=std::make_shared<std::string>(pJson["shopName"].asString());
        }
    }
    if(pJson.isMember("ownerId"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["ownerId"].isNull())
        {
            ownerid_=std::make_shared<int32_t>((int32_t)pJson["ownerId"].asInt64());
        }
    }
}

const int32_t &Shops::getValueOfShopid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(shopid_)
        return *shopid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Shops::getShopid() const noexcept
{
    return shopid_;
}
void Shops::setShopid(const int32_t &pShopid) noexcept
{
    shopid_ = std::make_shared<int32_t>(pShopid);
    dirtyFlag_[0] = true;
}
const typename Shops::PrimaryKeyType & Shops::getPrimaryKey() const
{
    assert(shopid_);
    return *shopid_;
}

const std::string &Shops::getValueOfShopname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(shopname_)
        return *shopname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Shops::getShopname() const noexcept
{
    return shopname_;
}
void Shops::setShopname(const std::string &pShopname) noexcept
{
    shopname_ = std::make_shared<std::string>(pShopname);
    dirtyFlag_[1] = true;
}
void Shops::setShopname(std::string &&pShopname) noexcept
{
    shopname_ = std::make_shared<std::string>(std::move(pShopname));
    dirtyFlag_[1] = true;
}
void Shops::setShopnameToNull() noexcept
{
    shopname_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &Shops::getValueOfOwnerid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(ownerid_)
        return *ownerid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Shops::getOwnerid() const noexcept
{
    return ownerid_;
}
void Shops::setOwnerid(const int32_t &pOwnerid) noexcept
{
    ownerid_ = std::make_shared<int32_t>(pOwnerid);
    dirtyFlag_[2] = true;
}
void Shops::setOwneridToNull() noexcept
{
    ownerid_.reset();
    dirtyFlag_[2] = true;
}

void Shops::updateId(const uint64_t id)
{
    shopid_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Shops::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "shopName",
        "ownerId"
    };
    return inCols;
}

void Shops::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getShopname())
        {
            binder << getValueOfShopname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getOwnerid())
        {
            binder << getValueOfOwnerid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Shops::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Shops::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getShopname())
        {
            binder << getValueOfShopname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getOwnerid())
        {
            binder << getValueOfOwnerid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Shops::toJson() const
{
    Json::Value ret;
    if(getShopid())
    {
        ret["shopId"]=getValueOfShopid();
    }
    else
    {
        ret["shopId"]=Json::Value();
    }
    if(getShopname())
    {
        ret["shopName"]=getValueOfShopname();
    }
    else
    {
        ret["shopName"]=Json::Value();
    }
    if(getOwnerid())
    {
        ret["ownerId"]=getValueOfOwnerid();
    }
    else
    {
        ret["ownerId"]=Json::Value();
    }
    return ret;
}

std::string Shops::toString() const
{
    return toJson().toStyledString();
}

Json::Value Shops::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getShopid())
            {
                ret[pMasqueradingVector[0]]=getValueOfShopid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getShopname())
            {
                ret[pMasqueradingVector[1]]=getValueOfShopname();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getOwnerid())
            {
                ret[pMasqueradingVector[2]]=getValueOfOwnerid();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getShopid())
    {
        ret["shopId"]=getValueOfShopid();
    }
    else
    {
        ret["shopId"]=Json::Value();
    }
    if(getShopname())
    {
        ret["shopName"]=getValueOfShopname();
    }
    else
    {
        ret["shopName"]=Json::Value();
    }
    if(getOwnerid())
    {
        ret["ownerId"]=getValueOfOwnerid();
    }
    else
    {
        ret["ownerId"]=Json::Value();
    }
    return ret;
}

bool Shops::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("shopId"))
    {
        if(!validJsonOfField(0, "shopId", pJson["shopId"], err, true))
            return false;
    }
    if(pJson.isMember("shopName"))
    {
        if(!validJsonOfField(1, "shopName", pJson["shopName"], err, true))
            return false;
    }
    if(pJson.isMember("ownerId"))
    {
        if(!validJsonOfField(2, "ownerId", pJson["ownerId"], err, true))
            return false;
    }
    return true;
}
bool Shops::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Shops::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("shopId"))
    {
        if(!validJsonOfField(0, "shopId", pJson["shopId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("shopName"))
    {
        if(!validJsonOfField(1, "shopName", pJson["shopName"], err, false))
            return false;
    }
    if(pJson.isMember("ownerId"))
    {
        if(!validJsonOfField(2, "ownerId", pJson["ownerId"], err, false))
            return false;
    }
    return true;
}
bool Shops::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Shops::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Users Shops::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from users where userId = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *ownerid_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Users(r[0]);
}

void Shops::getUsers(const DbClientPtr &clientPtr,
                     const std::function<void(Users)> &rcb,
                     const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from users where userId = ?";
    *clientPtr << sql
               << *ownerid_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Users(r[0]));
                    }
               }
               >> ecb;
}
