/**
 *
 *  Users.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::shopfront_db;

const std::string Users::Cols::_userId = "userId";
const std::string Users::Cols::_userName = "userName";
const std::string Users::Cols::_userPass = "userPass";
const std::string Users::Cols::_userEmail = "userEmail";
const std::string Users::primaryKeyName = "userId";
const bool Users::hasPrimaryKey = true;
const std::string Users::tableName = "users";

const std::vector<typename Users::MetaData> Users::metaData_={
{"userId","int32_t","int(11)",4,1,1,1},
{"userName","std::string","varchar(14)",14,0,0,1},
{"userPass","std::string","char(64)",0,0,0,1},
{"userEmail","std::string","varchar(320)",320,0,0,1}
};
const std::string &Users::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Users::Users(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["userId"].isNull())
        {
            userid_=std::make_shared<int32_t>(r["userId"].as<int32_t>());
        }
        if(!r["userName"].isNull())
        {
            username_=std::make_shared<std::string>(r["userName"].as<std::string>());
        }
        if(!r["userPass"].isNull())
        {
            userpass_=std::make_shared<std::string>(r["userPass"].as<std::string>());
        }
        if(!r["userEmail"].isNull())
        {
            useremail_=std::make_shared<std::string>(r["userEmail"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            username_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userpass_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            useremail_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Users::Users(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            username_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userpass_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            useremail_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Users::Users(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("userId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["userId"].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson["userId"].asInt64());
        }
    }
    if(pJson.isMember("userName"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["userName"].isNull())
        {
            username_=std::make_shared<std::string>(pJson["userName"].asString());
        }
    }
    if(pJson.isMember("userPass"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["userPass"].isNull())
        {
            userpass_=std::make_shared<std::string>(pJson["userPass"].asString());
        }
    }
    if(pJson.isMember("userEmail"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["userEmail"].isNull())
        {
            useremail_=std::make_shared<std::string>(pJson["userEmail"].asString());
        }
    }
}

void Users::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            username_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userpass_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            useremail_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Users::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("userId"))
    {
        if(!pJson["userId"].isNull())
        {
            userid_=std::make_shared<int32_t>((int32_t)pJson["userId"].asInt64());
        }
    }
    if(pJson.isMember("userName"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["userName"].isNull())
        {
            username_=std::make_shared<std::string>(pJson["userName"].asString());
        }
    }
    if(pJson.isMember("userPass"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["userPass"].isNull())
        {
            userpass_=std::make_shared<std::string>(pJson["userPass"].asString());
        }
    }
    if(pJson.isMember("userEmail"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["userEmail"].isNull())
        {
            useremail_=std::make_shared<std::string>(pJson["userEmail"].asString());
        }
    }
}

const int32_t &Users::getValueOfUserid() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userid_)
        return *userid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Users::getUserid() const noexcept
{
    return userid_;
}
void Users::setUserid(const int32_t &pUserid) noexcept
{
    userid_ = std::make_shared<int32_t>(pUserid);
    dirtyFlag_[0] = true;
}
const typename Users::PrimaryKeyType & Users::getPrimaryKey() const
{
    assert(userid_);
    return *userid_;
}

const std::string &Users::getValueOfUsername() const noexcept
{
    static const std::string defaultValue = std::string();
    if(username_)
        return *username_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getUsername() const noexcept
{
    return username_;
}
void Users::setUsername(const std::string &pUsername) noexcept
{
    username_ = std::make_shared<std::string>(pUsername);
    dirtyFlag_[1] = true;
}
void Users::setUsername(std::string &&pUsername) noexcept
{
    username_ = std::make_shared<std::string>(std::move(pUsername));
    dirtyFlag_[1] = true;
}

const std::string &Users::getValueOfUserpass() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userpass_)
        return *userpass_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getUserpass() const noexcept
{
    return userpass_;
}
void Users::setUserpass(const std::string &pUserpass) noexcept
{
    userpass_ = std::make_shared<std::string>(pUserpass);
    dirtyFlag_[2] = true;
}
void Users::setUserpass(std::string &&pUserpass) noexcept
{
    userpass_ = std::make_shared<std::string>(std::move(pUserpass));
    dirtyFlag_[2] = true;
}

const std::string &Users::getValueOfUseremail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(useremail_)
        return *useremail_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getUseremail() const noexcept
{
    return useremail_;
}
void Users::setUseremail(const std::string &pUseremail) noexcept
{
    useremail_ = std::make_shared<std::string>(pUseremail);
    dirtyFlag_[3] = true;
}
void Users::setUseremail(std::string &&pUseremail) noexcept
{
    useremail_ = std::make_shared<std::string>(std::move(pUseremail));
    dirtyFlag_[3] = true;
}

void Users::updateId(const uint64_t id)
{
    userid_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Users::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "userName",
        "userPass",
        "userEmail"
    };
    return inCols;
}

void Users::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUsername())
        {
            binder << getValueOfUsername();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserpass())
        {
            binder << getValueOfUserpass();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUseremail())
        {
            binder << getValueOfUseremail();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Users::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Users::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUsername())
        {
            binder << getValueOfUsername();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserpass())
        {
            binder << getValueOfUserpass();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUseremail())
        {
            binder << getValueOfUseremail();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Users::toJson() const
{
    Json::Value ret;
    if(getUserid())
    {
        ret["userId"]=getValueOfUserid();
    }
    else
    {
        ret["userId"]=Json::Value();
    }
    if(getUsername())
    {
        ret["userName"]=getValueOfUsername();
    }
    else
    {
        ret["userName"]=Json::Value();
    }
    if(getUserpass())
    {
        ret["userPass"]=getValueOfUserpass();
    }
    else
    {
        ret["userPass"]=Json::Value();
    }
    if(getUseremail())
    {
        ret["userEmail"]=getValueOfUseremail();
    }
    else
    {
        ret["userEmail"]=Json::Value();
    }
    return ret;
}

std::string Users::toString() const
{
    return toJson().toStyledString();
}

Json::Value Users::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserid())
            {
                ret[pMasqueradingVector[0]]=getValueOfUserid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUsername())
            {
                ret[pMasqueradingVector[1]]=getValueOfUsername();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserpass())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserpass();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getUseremail())
            {
                ret[pMasqueradingVector[3]]=getValueOfUseremail();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserid())
    {
        ret["userId"]=getValueOfUserid();
    }
    else
    {
        ret["userId"]=Json::Value();
    }
    if(getUsername())
    {
        ret["userName"]=getValueOfUsername();
    }
    else
    {
        ret["userName"]=Json::Value();
    }
    if(getUserpass())
    {
        ret["userPass"]=getValueOfUserpass();
    }
    else
    {
        ret["userPass"]=Json::Value();
    }
    if(getUseremail())
    {
        ret["userEmail"]=getValueOfUseremail();
    }
    else
    {
        ret["userEmail"]=Json::Value();
    }
    return ret;
}

bool Users::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("userId"))
    {
        if(!validJsonOfField(0, "userId", pJson["userId"], err, true))
            return false;
    }
    if(pJson.isMember("userName"))
    {
        if(!validJsonOfField(1, "userName", pJson["userName"], err, true))
            return false;
    }
    else
    {
        err="The userName column cannot be null";
        return false;
    }
    if(pJson.isMember("userPass"))
    {
        if(!validJsonOfField(2, "userPass", pJson["userPass"], err, true))
            return false;
    }
    else
    {
        err="The userPass column cannot be null";
        return false;
    }
    if(pJson.isMember("userEmail"))
    {
        if(!validJsonOfField(3, "userEmail", pJson["userEmail"], err, true))
            return false;
    }
    else
    {
        err="The userEmail column cannot be null";
        return false;
    }
    return true;
}
bool Users::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Users::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("userId"))
    {
        if(!validJsonOfField(0, "userId", pJson["userId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("userName"))
    {
        if(!validJsonOfField(1, "userName", pJson["userName"], err, false))
            return false;
    }
    if(pJson.isMember("userPass"))
    {
        if(!validJsonOfField(2, "userPass", pJson["userPass"], err, false))
            return false;
    }
    if(pJson.isMember("userEmail"))
    {
        if(!validJsonOfField(3, "userEmail", pJson["userEmail"], err, false))
            return false;
    }
    return true;
}
bool Users::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Users::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 14)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 14)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 320)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 320)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
